In [1]:
#Lógica de programação para a solução do desafio
#Passo 0 - Entender o desafio que você quer resolver
#Passo 1 - Importar a base de dados
#Passo 2 - Calcular o produto mais vendido (em quantidade)
#Passo 3 - Calcular o produto mais vendido (em feturamento)
#Passo 4 - Calcular a loja/estado que mais vendeu (em faturamento)
#Passo 5 - Calcular o ticket médio por loja/estado
#Passo 6 - Criar um gráfico/dashboard da loja/estado que mais vendeu (em faturamento)
#Passo 7 - Enviar um e-mail para o setor  responsável

In [32]:
import pandas as pd
import plotly.express as px

In [3]:
tabelas_vendas = pd.read_excel('Vendas_Base_de_Dados.xlsx')

In [4]:
tabelas_vendas.head()

   Cód.        Data            Loja       Produto  Quantidade  Valor Unitário
0     1   5/18/2022        Maranhão  Caixa de som           4              79
1     2   7/24/2022  Santa Catarina      Notebook           9            3789
2     3  12/20/2022  Rio de Janeiro      Notebook           3            3789
3     4   1/22/2022  Espírito Santo       Nobreak           9            1279
4     5   9/11/2022       Tocantins    Impressora           9             699

In [5]:
tabelas_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Cód.            15000 non-null  int64
 1   Data            15000 non-null  object
 2   Loja            15000 non-null  object
 3   Produto         15000 non-null  object
 4   Quantidade      15000 non-null  int64
 5   Valor Unitário  15000 non-null  int64
dtypes: int64(3), object(3)
memory usage: 703.3+ KB

In [6]:
tabelas_vendas.shape

(15000, 6)

In [7]:
tabelas_vendas.columns

Index(['Cód.', 'Data', 'Loja', 'Produto', 'Quantidade', 'Valor Unitário'], dtype='object')

In [8]:
tabelas_vendas['Quantidade'].value_counts()

Quantidade
1     1555
5     1550
3     1538
10    1534
6     1506
9     1474
7     1474
4     1469
8     1462
2     1438
Name: count, dtype: int64

In [9]:
tabelas_vendas['Quantidade'].mean()

np.float64(5.488466666666667)

In [10]:
tabelas_vendas['Loja'].value_counts()

Loja
São Paulo              4749
Rio de Janeiro         1449
Minas Gerais           1406
Paraná                  872
Pernambuco              787
Goiás                   710
Rio Grande do Sul       706
Bahia                   597
Distrito Federal        535
Santa Catarina          519
Espírito Santo          404
Ceará                   372
Pará                    327
Mato Grosso do Sul      211
Mato Grosso             192
Paraíba                 192
Amazonas                177
Rio Grande do Norte     168
Tocantins               124
Alagoas                 123
Maranhão                114
Piauí                    94
Sergipe                  60
Rondônia                 58
Roraima                  21
Amapá                    20
Acre                     13
Name: count, dtype: int64

In [11]:
#Calcular o produto mais vendido (em quantidade)
tb_quantidade_produto = tabelas_vendas.groupby('Produto').sum()
tb_quantidade_produto = tb_quantidade_produto[['Quantidade']].sort_values(by='Quantidade', ascending=False)
display(tb_quantidade_produto)

              Quantidade
Produto
Impressora         13285
Notebook           12930
Monitor             9923
Nobreak             6778
Tablet              6684
Teclado             6631
Webcam              6562
Caixa de som        6535
PC                  6518
Mouse               6481

In [19]:
#Calcular o produto mais vendido (em faturamento)
tabelas_vendas['Faturamento'] = tabelas_vendas['Quantidade'] * tabelas_vendas['Valor Unitário']
tabela_fat_prod = tabelas_vendas.groupby('Produto').sum()
tabela_fat_prod = tabela_fat_prod[['Faturamento']].sort_values(by='Faturamento', ascending=False)
tabela_fat_prod.head(5)

            Faturamento
Produto
Notebook       48991770
PC             38456200
Monitor        11907600
Impressora      9286215
Tablet          9016716

In [ ]:
#Calcular a loja/estado que mais vendeu (em faturamento)
tabela_loja = tabelas_vendas.groupby('Loja').sum() #Para aparecer somente número utilizar .sum(numeric_only=True)
tabela_loja = tabela_loja[['Faturamento']].sort_values(by='Faturamento', ascending=False)
tabela_loja.head(5)

                Faturamento
Loja
São Paulo          41018776
Rio de Janeiro     12274351
Minas Gerais       11491527
Paraná              7611645
Pernambuco          7041123

In [26]:
#Calcular o ticket médio por loja/estado
tabelas_vendas['Ticket Médio'] = tabelas_vendas['Valor Unitário']
tb_ticket_medio = tabelas_vendas.groupby('Loja').mean(numeric_only=True)
tb_ticket_medio = tb_ticket_medio[['Ticket Médio']].sort_values(by='Ticket Médio', ascending=False).round(2)
tb_ticket_medio.head()

                   Ticket Médio
Loja
Acre                    2142.77
Sergipe                 1735.33
Tocantins               1734.31
Rio Grande do Sul       1690.04
Pará                    1683.75

In [33]:
#Criar um gráfico/dashboard da loja/estado que mais vendeu (em faturamento)
grafico = px.bar(tabela_loja, y='Faturamento', x=tabela_loja.index)
grafico.show()

In [ ]:
#Enviar um email para o setor responsável